language: python

# Test on multiple os
matrix:
  include:
  - os: linux
    dist: xenial # python 3.7 not available on 'trusty'
    python:
    - "3.7"
    - "nightly"
    install: pip install -r requirements.txt
    script: pytest
  - os: osx
    python:
    - "3.6"
    - "3.7-dev"
    - "nightly"
    install: pip install -r requirements.txt
    script: pytest
 # - os: windows # Python not yet supported on windows
